# Generated by Django 5.1.6 on 2025-07-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fill_null_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
