# Generated by Django 5.1.6 on 2025-07-06 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('авария', 'авария'), ('инцидент', 'инцидент'), ('травма', 'травма'), ('пожар', 'пожар'), ('другое', 'другое')], max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('в работе', 'в работе'), ('завершено', 'завершено'), ('на рассмотрении', 'на рассмотрении')], default='в работе', max_length=16)),
                ('measures_taken', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
