# Generated by Django 5.1.6 on 2025-07-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('в работе', 'в работе'), ('завершено', 'завершено'), ('на рассмотрении', 'на рассмотрении')], default='в работе', max_length=16),
        ),
    ]
