# Generated by Django 5.1.6 on 2025-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
