# Generated by Django 5.1.6 on 2025-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
